# triggers a release or a release candidate based on the version defined in package.json

name: Release

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ bugfix/symbols-only-font-generation-release ]
    paths-ignore:
      - 'images/**'
      - '**.md'
      - '.all-contributorsrc'
      - 'chocolatey/**'
      - 'bin/scripts/lib/**'
      - 'Dockerfile'
      - 'install.ps1'
      - 'install.sh'
      - 'LICENSE'
      - 'package**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Workflow to build and install dependencies
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        font: ["NerdFontsSymbolsOnly"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '1'

      - name: Set release variables
        run: |
          cd -- "$GITHUB_WORKSPACE"
          cat package.json
          RELEASE_TAG_VERSION=$(cat package.json \
          | grep version \
          | head -1 \
          | awk -F: '{ print $2 }' \
          | sed 's/[",]//g')
          echo "RELEASE_TAG_VERSION=$RELEASE_TAG_VERSION" >> $GITHUB_ENV
          [[ "$RELEASE_TAG_VERSION" == *"-RC"* ]] && echo "RELEASE_CANDIDATE=true" || echo "RELEASE_CANDIDATE=false" >> $GITHUB_ENV

      # Install and setup Dependencies
      # @TODO cache the next 4 steps with actions/cache or upload
      - name: Setup core dependencies
        run: |
          sudo apt update -y -q
          sudo apt install software-properties-common -y -q
          sudo apt update -y -q
          sudo apt install fontforge -y -q
          sudo apt install python3-fontforge -y -q

      - name: Setup additional dependencies
        run: |
          pip install fonttools --quiet

      - name: Build FreeType from source
        run: |
          wget http://downloads.sourceforge.net/project/freetype/freetype2/2.7/freetype-2.7.tar.gz --quiet
          tar -zxf freetype-2.7.tar.gz
          cd freetype-2.7
          ./configure
          make --quiet
          sudo make install --quiet

      - name: Build Harfbuzz from source
        run: |
          wget http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.3.4.tar.bz2 --quiet
          tar -xjf harfbuzz-1.3.4.tar.bz2
          cd harfbuzz-1.3.4
          ./configure
          make --quiet
          sudo make install --quiet

      - name: Verify setup
        run: |
          fontforge --version
          fontforge --version 2>&1 | grep libfontforge | awk '{print $NF}'

      - name: Standardize the readme files
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ./standardize-and-complete-readmes.sh "${{ matrix.font }}"

      - name: Patch all the variations of the font family
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          fontforge --script ../../font-patcher --version
          ./gotta-patch-em-all-font-patcher\!.sh "${{ matrix.font }}"

      - name: Generate fontconfig and casks
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ./generate-fontconfig.sh
          ./generate-casks.sh "${{ matrix.font }}"

      - name: Upload patched fonts as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: patched-fonts
          # adding multiple paths (i.e. LICENSE) is a workaround to get a least common ancestor
          # of the root directory for artifact path purposes
          path: |
            patched-fonts/${{ matrix.font }}
            LICENSE

  commit:
    name: Commit and push patched fonts to the repo
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download patched fonts from build
        id: download-patched-fonts
        uses: actions/download-artifact@v2
        with:
          name: patched-fonts
          path: .

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'patched-fonts'
          message: Rebuilds patched fonts
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
